services:
  prod-frontend: 
    build: P2I/
    ports:
      - 80:3000
    command: "sh -c 'sh ./configure.sh && npx serve dist/p2-i -p 3000'"
    environment:
      - URL_BACKEND 

  prod-backend:
    build: P2I-backend/
    command: "bash -c 'bash ./generateSecret.sh && dotnet P2I-backend.dll'"
    volumes:
      - p2ikillerapp-db:/app/BDD
    ports: 
      - 8081:8080


volumes:
  p2ikillerapp-db:
    name: p2ikillerapp-db
    external: true