services:
  dev-backend:
    build:
      context: ./P2I-backend
      dockerfile: DockerfileDev
    command: ["dotnet", "watch", "run"]
    ports:
      - "5149:5149"
    volumes:
      - ./P2I-backend:/app
      - /app/bin
      - /app/obj
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5149
  dev-frontend:
    build: ./P2I
    ports:
      - "4200:4200"
    volumes:
      - ./P2I:/usr/src/app
    command: ["npx", "ng", "serve", "--host", "0.0.0.0"]
